name: Relife
description: an app targeted for socially challenged people.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  outline_gradient_button: ^2.0.1+1
  gradient_borders: ^1.0.0
  flutter_svg_provider: ^1.0.7
  readmore: ^2.2.0
  intl: ^0.18.0
  url_launcher: ^6.2.5
  walletconnect_dart: ^0.0.11
  web3dart: ^2.7.1
  web3modal_flutter: ^3.0.1
  slider_button: ^2.1.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Space Grotesk
      fonts: 
        - asset: assets/fonts/SpaceGroteskBold.ttf
          weight: 700
        - asset: assets/fonts/SpaceGroteskRegular.ttf
          weight: 400
        - asset: assets/fonts/SpaceGroteskMedium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGroteskLight.ttf
          weight: 300
    - family: customfont
      fonts:
        - asset: assets/fonts/death-note/hoolla.ttf
    - family: new
      fonts:
        - asset: assets/fonts/Fasthand-Regular.ttf
    - family: Kavoon
      fonts: 
        - asset: assets/fonts/KavoonRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterBold.ttf
          weight: 700
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600

